### PR TITLE
Add IPv6 support

### PR DESCRIPTION
**Pull request by suxinde2009**
Add IPv6 support

### CODE REVIEW

**Comment by kmilitagaitanm** [comment]
Please review it. we really need this change

**Comment by cezheng** [comment]
This change ain't necessary at all.
Refer to my explanation here

https://github.com/tonymillion/Reachability/issues/136#issuecomment-220847178

**Comment by DanielLimaDF** [comment]
My app was rejected due to ipv6 problems, i used this changes and the app was accepted. Thank you @suxinde2009 

@cezheng I saw your explanation and makes sense, but it seems that in some cases (
Probably because of dns configuration problems on the server) It may be necessary to follow the recommendations made by apple here: https://developer.apple.com/library/content/documentation/NetworkingInternetWeb/Conceptual/NetworkingOverview/UnderstandingandPreparingfortheIPv6Transition/UnderstandingandPreparingfortheIPv6Transition.html

Recommendations:

**If your code handles IPv4 types, make sure the IPv6 equivalents are handled too.**
<table class="graybox" border="0" cellspacing="0" cellpadding="5"><tbody><tr><th scope="col" class="TableHeading_TableRow_TableCell"><p>IPv4</p></th><th scope="col" class="TableHeading_TableRow_TableCell"><p>IPv6</p></th></tr><tr><td scope="row"><p><code>AF_INET</code></p></td><td><p><code>AF_INET6</code></p></td></tr><tr><td scope="row"><p><code>PF_INET</code></p></td><td><p><code>PF_INET6</code></p></td></tr><tr><td scope="row"><p><code>struct in_addr</code></p></td><td><p><code>struct in_addr6</code></p></td></tr><tr><td scope="row"><p><code>struct sockaddr_in</code></p></td><td><p><code>struct sockaddr_in6</code></p></td></tr><tr><td scope="row"><p><code>kDNSServiceProtocol_IPv4</code></p></td><td><p><code>kDNSServiceProtocol_IPv6</code></p></td></tr></tbody></table>

**Comment by cdeust** [comment]
There is a problem with the declaration of the ipv6 for ReachibilityForLocalWiFi, on iOS 10.

localWifiAddress.sin6_addr.s_addr = htonl(IN_LINKLOCALNETNUM);
Should be instead :
localWifiAddress.sin6_addr = in6addr_linklocal_allnodes

**Pull request closed without merging**
